// ======= CONFIG (edit these!) =======
export const PIN_CODE = '200125'; // required 6-digit pin

export const PLAYLIST = [
  // Add new songs or reorder existing ones here to adjust the playlist sequence.
  { id: '06-XXOTP3Gc', title: 'Shane Filan - Beautiful in White' },
  { id: 'OT5msu-dap8', title: 'Backstreet Boys - Shape of My Heart' },
  { id: 'Qy7z_oiN6nQ', title: "George Benson - Nothing's Gonna Change My Love For You" },
  { id: 'DXvMT_mVbqw', title: 'K-Ci & JoJo - All My Life' },
  { id: 'Ip6cw8gfHHI', title: 'd4vd - Here With Me' },
  { id: 'KNZH-emehxA', title: "Shania Twain - You're Still The One" },
  { id: 'HeK1zQFJtXE', title: 'Tamia - Officially Missing You' },
  { id: '8MG--WuNW1Y', title: 'Wei Bird - 如果可以' },
  { id: 'S_E2EHVxNAE', title: 'Richard Marx - Right Here Waiting' },
  { id: 'Ju8Hr50Ckwk', title: "Alicia Keys - If I Ain't Got You" },
  { id: 'iBrOFd1wDuQ', title: '羅志祥 - 愛不單行' },
  { id: 'd4_QuMkOdCI', title: 'Eric Clapton - Wonderful Tonight' },
  { id: 'XJ1Jigjg1wo', title: 'Ardhito Pramono - Waking Up Together With You' },
  { id: 'Xct1EdyHMWw', title: 'Yahya - keepyousafe' },
  { id: '5W0UH4VbptE', title: 'PK Haeman - Evergreen Part 2' },
  { id: '7KVxjQUCyn0', title: 'Mariah Carey, Joe, 98 Degrees - Thank God I Found You' },
  { id: 'ulOb9gIGGd0', title: 'Westlife - My Love' },
  { id: '2VInZQdh1eY', title: 'M2M - Pretty Boy' },
  { id: 'psN0NH8IcbQ', title: 'Brian McKnight - Back At One' },
  { id: 'IlrXHkPvn8I', title: 'Celine Dion - Because You Loved Me' },
  { id: 'ZnOAK04tJhc', title: 'Westlife - I Lay My Love on You' },
  { id: 'K1uNjmxJQUo', title: 'The Pussycat Dolls - Stickwitu' },
  { id: '1WCIrw85zbQ', title: 'Westlife - I Wanna Grow Old with You' },
  { id: 'KnJfMzsyDS0', title: 'Inquisitive feat. Hannah Ying - 不得不爱' },
  { id: 'WCM_eSgaK6o', title: 'Vic Chou - Make a Wish' },
  { id: 'IvRQBrOY6Bk', title: '김동률 - 취중진담' },
  { id: 'V9PVRfjEBTI', title: 'Billie Eilish - BIRDS OF A FEATHER' },
  { id: 'sKoy0EA7pyI', title: 'LEONNE - Hi, Leanne' },
  { id: 'B84pjvZ5E1E', title: 'LEONNE - Hi, Leonore' },
  { id: 'XoiuewknIM0', title: 'LEONNE - Hujan Kala Itu' },
  { id: 'Lij6cfG5mew', title: 'LEONNE - Tulip & Edelweiss' },
  { id: 'wxOWbEIWEpk', title: "LEONNE - It's Only You Baby" },
  { id: 'kHLy37vDeRI', title: 'LEONNE - Cinta & Luka' },
];

export const loveLetters = [
  {
    ring: 'images/Ring/ring_01-ayodance-sugar.png',
    letter: 'images/LP Love Letter ♡/Chapter 0 - Sugar - 20.01.2025.jpg',
    chapter: 'Chapter 0',
    flavor: 'Sugar',
    date: '20.01.2025',
  },
  {
    ring: 'images/Ring/ring_02-ayodance-sweet.png',
    letter: 'images/LP Love Letter ♡/Chapter 1 - Sweet - 20.01.2025.jpg',
    chapter: 'Chapter 1',
    flavor: 'Sweet',
    date: '20.01.2025',
  },
  {
    ring: 'images/Ring/ring_03-ayodance-candy.png',
    letter: 'images/LP Love Letter ♡/Chapter 2 - Candy - 21.01.2025.jpg',
    chapter: 'Chapter 2',
    flavor: 'Candy',
    date: '21.01.2025',
  },
  {
    ring: 'images/Ring/ring_04-ayodance-cherry.png',
    letter: 'images/LP Love Letter ♡/Chapter 3 - Cherry - 21.01.2025.jpg',
    chapter: 'Chapter 3',
    flavor: 'Cherry',
    date: '21.01.2025',
  },
  {
    ring: 'images/Ring/ring_05-ayodance-strawberry.png',
    letter: 'images/LP Love Letter ♡/Chapter 4 - Strawberry - 22.01.2025.jpg',
    chapter: 'Chapter 4',
    flavor: 'Strawberry',
    date: '22.01.2025',
  },
  {
    ring: 'images/Ring/ring_06-ayodance-honey.png',
    letter: 'images/LP Love Letter ♡/Chapter 5 - Honey - 23.01.2025.jpg',
    chapter: 'Chapter 5',
    flavor: 'Honey',
    date: '23.01.2025',
  },
  {
    ring: 'images/Ring/ring_07-ayodance-chocholate.png',
    letter: 'images/LP Love Letter ♡/Chapter 6 - Chocolate - 24.01.2025.jpg',
    chapter: 'Chapter 6',
    flavor: 'Chocolate',
    date: '24.01.2025',
  },
  {
    ring: 'images/Ring/ring_08-ayodance-cupcake.png',
    letter: 'images/LP Love Letter ♡/Chapter 7 - Cupcake - 25.01.2025.jpg',
    chapter: 'Chapter 7',
    flavor: 'Cupcake',
    date: '25.01.2025',
  },
  {
    ring: 'images/Ring/ring_09-ayodance-brownies.png',
    letter: 'images/LP Love Letter ♡/Chapter 8 - Brownies - 30.01.2025.jpg',
    chapter: 'Chapter 8',
    flavor: 'Brownies',
    date: '30.01.2025',
  },
  {
    ring: 'images/Ring/ring_10-ayodance-tiramisu.png',
    letter: 'images/LP Love Letter ♡/Chapter 9 - Tiramisu - 30.01.2025.jpg',
    chapter: 'Chapter 9',
    flavor: 'Tiramisu',
    date: '30.01.2025',
  },
  {
    ring: 'images/Ring/ring_11-ayodance-sakura.png',
    letter: 'images/LP Love Letter ♡/Chapter 10 - Sakura - 01.02.2025.jpg',
    chapter: 'Chapter 10',
    flavor: 'Sakura',
    date: '01.02.2025',
  },
  {
    ring: 'images/Ring/ring_12-ayodance-roses.png',
    letter: 'images/LP Love Letter ♡/Chapter 11 - Roses - 03.02.2025.jpg',
    chapter: 'Chapter 11',
    flavor: 'Roses',
    date: '03.02.2025',
  },
  {
    ring: 'images/Ring/ring_13-ayodance-edelweiss.png',
    letter: 'images/LP Love Letter ♡/Chapter 12 - Edelweiss - 14.02.2025.jpg',
    chapter: 'Chapter 12',
    flavor: 'Edelweiss',
    date: '14.02.2025',
  },
  {
    ring: 'images/Ring/ring_14-ayodance-lobelia.png',
    letter: 'images/LP Love Letter ♡/Chapter 13 - Lobelia - 21.03.2025.jpg',
    chapter: 'Chapter 13',
    flavor: 'Lobelia',
    date: '21.03.2025',
  },
  {
    ring: 'images/Ring/ring_15-ayodance-peppermint.png',
    letter: 'images/LP Love Letter ♡/Chapter 14 - Peppermint - 22.04.2025.jpg',
    chapter: 'Chapter 14',
    flavor: 'Peppermint',
    date: '22.04.2025',
  },
  {
    ring: 'images/Ring/ring_16-ayodance-iris.png',
    letter: 'images/LP Love Letter ♡/Chapter 15 - Iris - 29.09.2025.jpg',
    chapter: 'Chapter 15',
    flavor: 'Iris',
    date: '29.09.2025',
  },
];

export const timelineData = [
  { title: 'The day our hearts connected', date: '2024-10-15', note: 'Our story started here.' },
  { title: 'First commitment', date: '2025-01-20', note: 'Nerves, laughter, and butterflies.' },
  { title: 'First breakup', date: '2025-05-22', note: 'We learned, healed, and chose love again.' },
  { title: 'Final commitment', date: '2025-06-26', note: 'Together, stronger, softer.' },
];

export const quotes = [
  'You are my today and all of my tomorrows.',
  'In your smile, I see something more beautiful than the stars.',
  'I love you more than words can express.',
  'Every love story is beautiful, but ours is my favorite.',
  'I choose you. And I will choose you, over and over.',
];
